### ISSUE TITLE
Support Apache Solr 5.x

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-solr#10]
5.x is another large change to the entire Solr deployment/configuration process, as it no longer supports other Java servlet containers out of the box, and relies instead on built-in tooling.

The recommended setup uses a shell script with command line flags, but we can do better than that (what is this, 1999? Who logs into servers anymore?).

See:

  - [Running Solr](https://cwiki.apache.org/confluence/display/solr/Running+Solr)
  - [Taking Solr to Production](https://cwiki.apache.org/confluence/display/solr/Taking+Solr+to+Production)

I did a lot of the ground work in #8, but there are still some things that need to be changed to get 5.x deployed and configured correctly out of the box. So far, since none of the projects I'm working on even have rudimentary support for 5.x (they're all only recently updated for later versions of _4.x_!), this isn't a pressing issue. But I would like to be able to get the role to support at least 4.x and 5.x, if not 3/4/5.

**Comment by alanlavintman** [comment]
Geerling, i need support for solr 5. Took a look at your role and i would like to work it out a bit. 
What do you say if we use the service installation script instead of the one you wrote?

**Comment by arknoll** [comment]
FWIW, solr 5.x support is very important for Drupal 8 search_api_solr. 4.x will work, however, the new search_api_solr architecture will allow you to configure solr via the drupal UI if you are using solr 5.x.

**Comment by geerlingguy** [comment]
> The new search_api_solr architecture will allow you to configure solr via the drupal UI if you are using solr 5.x.

Heh... something I _personally_ would rather not see happen; letting site admins do things that affect the search index is an idea that can end poorly :)

But I understand and would like to get to adding Solr 5 support to the upstream role soon. The main problem is that a lot of little bits of the installation/configuration has changed, enough to where the 3.x/4.x structure that's currently in place will need to be replaced in a backwards-compatible way :(

**Comment by geerlingguy** [comment]
Doing a little work on this now...

**Comment by geerlingguy** [comment]
Pushed up a commit that's so far only tested on Debian. Going to do some testing on RedHat and also update tests to use Docker and test a bunch more things.

**Comment by geerlingguy** [comment]
I can also get rid of the custom init script by using Solr's built-in installation script—see "Run the Solr Installation Script" on this page: https://cwiki.apache.org/confluence/display/solr/Taking+Solr+to+Production
