### ISSUE TITLE
Consider updating default solr version

### ISSUE THREAD

**Issue by steveWinter** [geerlingguy/ansible-role-solr#100]
Installing solr today using this role along with the associated [java role](https://github.com/geerlingguy/ansible-role-java) I ran into issues on Ubuntu 18.04.

By default the java role will install a JDK which is too new for solr 7.1.0 the default here. Specifying the version as 7.4.0 in my local config solved that, but it would be nice if the 'defaults' played well with each other (unless there's some reason not to do this?)

**Comment by geerlingguy** [comment]
I will hopefully get to this soon; but note that I only get around to version bumps in roles like this once in a blue moon (unless there's a new major version that I want to add support for).

It's always best (IMO) to explicitly set the version you want in your playbook's variables, even if it's the same as the current version of the role.

**Comment by geerlingguy** [comment]
Updated to 7.4.0!
