### ISSUE TITLE
solr_service_state: stopped does not work

### ISSUE THREAD

**Issue by janhoy** [geerlingguy/ansible-role-solr#104]
Trying to tell the role not to start Solr using `solr_service_state: stopped` since I want to do some more config tasks and then start solr in `post_tasks`.

However, the role expects Solr to be running when querying for cores, so this is not possible. The core stuff should not be run if you ask for Solr to not start.

**Comment by geerlingguy** [comment]
That would be ideal; I won't have time to work on fixing it though, at least not in the next few weeks/months. If you have a PR I would consider it.

**Comment by janhoy** [comment]
I solved it so far with a separate post_task which stops Solr etc..
