### ISSUE TITLE
Your Linux distribution is not supported by this script on MacOS docker

### ISSUE THREAD

**Issue by adborden** [geerlingguy/ansible-role-solr#105]
Testing our playbooks with [molecule](https://molecule.readthedocs.io/en/latest/) on docker, but the role fails with this error. The kernel version string used by MacOS docker doesn't match anything the install script recognizes, so it fails. Running on a linux host (ubuntu) works fine.

```
    TASK [geerlingguy.solr : Run Solr installation script.] ************************
    fatal: [solr-catalog]: FAILED! => {"changed": true, "cmd": "/root/solr-5.5.5/bin/install_solr_service.sh /root/solr-5.5.5.tgz -i /opt -d /var/solr -u solr -s solr -p 8983", "delta": "0:00:00.277506", "end": "2018-11-16 22:09:24.961198", "msg": "non-zero return code", "rc": 1, "start": "2018-11-16 22:09:24.683692", "stderr": "\nERROR: Your Linux distribution (Linux version 4.9.93-linuxkit-aufs (root@856d34d1168e) (gcc version 6.4.0 (Alpine 6.4.0) ) #1 SMP Wed Jun 6 16:55:56 UTC 2018) not supported by this script!\nYou'll need to setup Solr as a service manually using the documentation provided in the Solr Reference Guide.", "stderr_lines": ["", "ERROR: Your Linux distribution (Linux version 4.9.93-linuxkit-aufs (root@856d34d1168e) (gcc version 6.4.0 (Alpine 6.4.0) ) #1 SMP Wed Jun 6 16:55:56 UTC 2018) not supported by this script!", "You'll need to setup Solr as a service manually using the documentation provided in the Solr Reference Guide."], "stdout": "", "stdout_lines": []}

    PLAY RECAP *********************************************************************
    solr-catalog               : ok=9    changed=5    unreachable=0    failed=1
```

You can repro it by cloning https://github.com/GSA/datagov-deploy-solr

```shell
$ make setup
$ make test
```

**Comment by geerlingguy** [comment]
@adborden - macOS is not a supported platform for installing this role—but it sounds like you're trying to install it within Docker within macOS (which is what I do).

Note that the role includes molecule tests, which work great for me both on macOS (with Docker for Mac) and Linux (with docker-ce) on CentOS, Ubuntu, etc.

It looks like your default molecule file is trying to run `ubuntu:trusty`. Also, it looks like you seem to be maintaining your own role, maybe? Is it a fork of this role? Please check out this role's molecule configuration for a working reference point.

For general playbook support/usage, I would recommend asking on the Ansible Project mailing list, or in the molecule issue queues.

Finally, the particular error (Solr installer not recognizing the platform) indicates that Solr is not able to determine what kind of OS it's on, and that's a Solr-specific issue.

See also: https://github.com/geerlingguy/solr-container/issues/8 — this is not a problem with this role, it looks like, but with the build environment; solr's 5.x install script doesn't know about a lot of platforms, so you have to figure out a way to work around it.

**Comment by adborden** [comment]
Thanks for the extra info! We created our own role specific to our environment and configuration that includes this one. I'll take a closer look at how you worked around the issue, because it's the same problem.

**Comment by triwats** [comment]
@adborden - did you do some magic to get this working in the end? Or did you just get rid of your macbook? I've had a look at the datagov repository but I can't see anything that would prevent this from being an issue. I suppose I could just test everything against the Gitlab environment to get around the kernel version exposed on MacOS, but seems a bit heavy handed.
