### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by p0nt** [geerlingguy/ansible-role-solr#115]
I believe there is a problem.

During installation.yaml we start the installation.sh script with the -n parameter because the version of solr is above 6.3.0, but in the cores.yaml file which comes after installation.yaml it is trying to connect to the localhost solr while it have not been started after installation due to the -n parameter set on versions above 6.3.0.

Shouldnt solr be started after installation to make sure cores.yaml is not giving errors and the rest of the playbook is not run?

**Comment by geerlingguy** [comment]
Is there an error message that you're getting or a problem you've encountered that prompted this issue? I haven't had any trouble with the role on my servers or test environments lately, but I could be doing something that masks the issue for me.
