### ISSUE TITLE
Does not work with systemd

### ISSUE THREAD

**Issue by relaxnow** [geerlingguy/ansible-role-solr#12]
Thank you for this role! I tested out using this role with Debian wheezy but it looks like that is unsupported?

```
TASK: [geerlingguy.solr | Ensure solr is started and enabled on boot.] ******** 
failed: [33.33.33.24] => {"failed": true}
msg: update-rc.d: error: solr Default-Start contains no runlevels, aborting.
```

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.5 (wheezy)
Release:	7.5
Codename:	wheezy
```

**Comment by mroest** [comment]
I've run into the same issue. Seems that i can not find the default run level. Probably something to do with my vagrant/virtualbox setup.

If you add the run level which in my case is level 2 all works fine. Add the run level param to init-script.yml

```yml
- name: Ensure solr is started and enabled on boot.
  service: name=solr state=started enabled=yes runlevel=2
```

**Comment by geerlingguy** [comment]
@relaxnow / @mroest - Now that the default installation has changed with Solr 5.x/6.x, can you see if that resolves the issue? Solr manages its own init setup at this point, and it should work with systemd out of the box.

**Comment by geerlingguy** [comment]
(Closing for now—please let me know and we'll reopen if it's still an issue).
