### ISSUE TITLE
Support for separating core configuration and data

### ISSUE THREAD

**Issue by seboss666** [geerlingguy/ansible-role-solr#122]
Hello,
I was asked to deploy a solr server that can separate core configuration and data (default is to include configuration and data inside the core folder). I see in the /etc/default/solr.in.sh that there is a "SOLR_DATA_HOME" variable for that, but it does not seem possible to use it with the current role capabilities and configuration variable.

I'm not really at ease with solr and i'm not even sure if only this variable is enough, but how could we include this support in the role ?

**Comment by geerlingguy** [comment]
I generally keep my data and config in the same core folder, so it's not a feature I'd add myself. But if someone were to add the functionality to the role in a simple way and make sure that works well, I may be willing to merge that.

**Comment by seboss666** [comment]
I've modified locally the role to try it, just to test if the service was taking the variable locally. It seems to work, I let the web agency validate if it's working as they requested, and I may propose a pull request with some additional bits (in this case, the data folder already exists, but we need to ensure that).

The main culprit I see is that by default, the full core configuration and data are copied in the home folder, and data gets recreated in the data folder after service restart, leaving with two data folder that can be confusing.
