### ISSUE TITLE
Setting solr_remove_cruft: true disallows creating additional cores

### ISSUE THREAD

**Issue by Cheaternl** [geerlingguy/ansible-role-solr#125]
After successfully installing SOLR via this role, you can remove the example folder by specifying

`solr_remove_cruft: true`

This, however makes it unable to add additional cores via this role, by adding names to the cores list.

```
solr_cores:
        - collection12
        - collection34
```
Where I added collection34 and ran this role again.
The error that you would get is:

```
TASK [geerlingguy.solr : Ensure core configuration directories exist.] *********************************************************************************************************************************
skipping: [localhost] => (item=collection12)
failed: [localhost] (item=collection34) => {"ansible_loop_var": "item", "changed": true, 
  "cmd": ["cp", "-r", "/opt/solr/example/files/conf/", "/var/solr/data/collection34/"], 
  "delta": "0:00:00.010478", "end": "2022-02-13 14:23:11.426554", "item": "collection34", 
  "msg": "non-zero return code", "rc": 1, "start": "2022-02-13 14:23:11.416076", 
  "stderr": "cp: cannot stat '/opt/solr/example/files/conf/': No such file or directory", 
 "stderr_lines": ["cp: cannot stat '/opt/solr/example/files/conf/': No such file or directory"], 
  "stdout": "", "stdout_lines": []}
```

I suggest that everything from `/example` is removed, except folder `/example/files/conf/` in task named `Remove example dir, if not needed.` or that a line is added in the readme after `solr_remove_cruft`, stating that no additional cores can be created via this role **after** initial setup and `solr_remove_cruft` is set to `true` (making this role not 100% idempotent).

**Comment by geerlingguy** [comment]
I think adding in a line in the docs would be adequate—I mostly added this feature for those (like me) using the role to build a Solr Docker container (to keep the size down) :)
