### ISSUE TITLE
Download directory and temporary directory should be distinct

### ISSUE THREAD

**Issue by frgomes** [geerlingguy/ansible-role-solr#14]
Imagine a scenario where you provide all binary archives and other external resources on a _read-only_ NFS server, for example. In this scenario, you would like to _read_ archives from NFS but expand their contents somewhere else.

In other words, create an additional `{{ solr_downloads }}` which is intended to keep the download binary. If it is already there, like in the example of a read-only NFS server, nothing needs to be downloaded.

**Comment by geerlingguy** [comment]
Closing in favor of #58—with that, you should not need to preserve the downloaded Solr archive anymore.
