### ISSUE TITLE
Context needs to be updated on the /etc/init.d/solr folder to allow solr to start

### ISSUE THREAD

**Issue by circuscowboy** [geerlingguy/ansible-role-solr#142]
with /etc/init.d/solr selinux does not allow solr to start without changing the context.

Ansible error - Unable to start service solr: Job for solr.service failed because the control process exited with error code.
on TASK [geerlingguy.solr : Ensure solr is started and enabled on boot if configured.]

Can be solve by the following linux command:

sudo chcon -v system_u:object_r:bin_t:s0 /etc/init.d/solr

Source if info (comments of the first answer): https://unix.stackexchange.com/questions/592473/systemd-su-permission-denied-in-etc-init-d-scripts

**Comment by liverwust** [comment]
Alternatively, it is possible to run the following `restorecon` command to reset the context to the one defined in [the SELinux Reference Policy](https://github.com/SELinuxProject/refpolicy/blob/af26e636973bff8494e2ed2f93795bde8e2d94e7/policy/modules/system/init.fc):

`# ls -lZ /etc/rc.d/init.d/solr`
`-rwxr--r--. 1 root root unconfined_u:object_r:etc_t:s0      2711 May 15 18:59 solr`
`restorecon -F /etc/rc.d/init.d/solr`  <-- **run this command**
`# ls -lZ /etc/rc.d/init.d/solr`
`-rwxr--r--. 1 root root system_u:object_r:initrc_exec_t:s0 2711 May 15 18:59 /etc/rc.d/init.d/solr`

(See how the context changes from _etc_t_ to _initrc_exec_t_, which does have permission to run _su_.)

Either way, I think this is probably going away in newer versions of Solr with the resolution of [SOLR-10905](https://issues.apache.org/jira/browse/SOLR-10905) (Linux install script should move to systemd). I am stuck on the 8.x major version branch and so need to keep using the sysvinit wrapper.
