### ISSUE TITLE
Init script behaviour

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-solr#15]
Current service behaviour:

User | start | stop | status | restart
----- | ----- | ----- | ------ | -------
root | OK | OK | OK | OK
solr | Error | OK | OK | Error
other | Error | OK | OK | Error

Desired service behaviour:

User | start | stop | status | restart
----- | ----- | ----- | ------ | ------
root | OK | OK | OK | OK
solr | OK | OK | OK | OK
other | Message | Message | OK | Message

Suggestions:
- allow solr user to start solr by removing "--user" option from daemon when current user equals solr user.
- disallow stopping of solr by non-root, non-solr users.
- provide "invalid" users with an informative message

Comments?

**Comment by geerlingguy** [comment]
I'm going to close this at this point, as the init file will now be managed by Solr itself if using a supported version (e.g. 5.x or 6.x).
