### ISSUE TITLE
Init script wrong user

### ISSUE THREAD

**Issue by raistlin** [geerlingguy/ansible-role-solr#20]
I have a strange problem, after installing this role on a Debian Jessie, daemon is started with user 'root', and error ````org.apache.solr.common.SolrException: java.io.FileNotFoundException: /var/solr/collection1/data/tlog/tlog.0000000000000000000```` is displayed at log console on Solr admin. I need to manually stop daemon and run ````su -c "/etc/init.d/solr start solr" solr```` to run daemon with solr user at least once. And only then data directory is created and initializated.

I expected process owner to be solr always, even when we run ````service solr start```` as root.

**Comment by geerlingguy** [comment]
Hmm... I haven't encountered this error before; when you create the collection, is the directory `/var/solr/collection1/data` owned by `solr:solr` or by another user?

**Comment by raistlin** [comment]
The whole directory /var/solr/collection1/data does not exists.

2015-12-04 16:25 GMT+01:00 Jeff Geerling <notifications@github.com>:

> Hmm... I haven't encountered this error before; when you create the
> collection, is the directory /var/solr/collection1/data owned by solr:solr
> or by another user?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geerlingguy/ansible-role-solr/issues/20#issuecomment-161994135>
> .
>



-- 
Raúl Ferriz
Ingeniero Técnico en Informática

**Comment by geerlingguy** [comment]
When you install Solr, how do you set up/configure your solr core directories? I generally create the dirs for the first core or two (in a multicore installation) as part of the general setup.

Also see how it works in https://github.com/geerlingguy/ansible-vagrant-examples/tree/master/solr

**Comment by geerlingguy** [comment]
I'm going to close this at this point, as the init file will now be managed by Solr itself if using a supported version (e.g. 5.x or 6.x).

(See related: https://github.com/geerlingguy/ansible-role-solr/issues/15)
