### ISSUE TITLE
Support Apache Solr 6

### ISSUE THREAD

**Issue by gmcdowell** [geerlingguy/ansible-role-solr#23]
I see that there is already discussions around v5. Thoughts on v6?

**Comment by geerlingguy** [comment]
Gaaaah! I'm just getting things onto 5.x finally. Didn't even realize 6 was a thing.

**Comment by gmcdowell** [comment]
Ah yes. I'll have a crack at it as I'm currently working on a project that requires v6. Will fork now. Any conventions you'd like me to be aware of?

**Comment by geerlingguy** [comment]
I'm actually taking a look at the 5.x issue right now, and might have something working to push up later—the main thing is, _if at all possible_, I want to still support 4.x at least, and hopefully 3.x too. But I'm willing to drop 3.x support if that's too crazy.

**Comment by geerlingguy** [comment]
5.x is now working... testing 6.0.1 now.

**Comment by gmcdowell** [comment]
Legend.

I’m happy to test once you done.



On 31 May 2016 at 15:03, Jeff Geerling <notifications@github.com> wrote:

> 5.x is now working... testing 6.0.1 now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geerlingguy/ansible-role-solr/issues/23#issuecomment-222582621>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJog2OQaCbEAhar3r742DdOTTypNkDM8ks5qG6UPgaJpZM4IoBT8>
> .
>



-- 
_________________________________

Greg McDowell

Oxigeno Online

**Comment by geerlingguy** [comment]
`master` branch should be working with 3, 4, 5, and 6 now :)

I'll tag a release once I finish up another small tweak or two!

**Comment by gmcdowell** [comment]
Man that was fast ;)

On 31 May 2016 at 15:22, Jeff Geerling <notifications@github.com> wrote:

> master branch should be working with 3, 4, 5, and 6 now :)
>
> I'll tag a release once I finish up another small tweak or two!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geerlingguy/ansible-role-solr/issues/23#issuecomment-222584288>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJog2OdjDe5ev24W6RSxtB8Zdo2Zu9C2ks5qG6lxgaJpZM4IoBT8>
> .
>



-- 
_________________________________

Greg McDowell

Oxigeno Online
