### ISSUE TITLE
httplib2 error in release 3.1.0 on provisioning

### ISSUE THREAD

**Issue by Rade333** [geerlingguy/ansible-role-solr#31]
Hi there,

I updated my solr role to the newest release, 3.1.0 and when provisioning I encountered this error:

![Alt text](https://monosnap.com/file/hgltj60p5aZv9uLcU5aSpv0Pc5AJn0.png)

Once I downgraded to 3.0.0 provisioning works again.

Sorry that I don't have any more detailed info right now, please ask if you want to know something specific about my setup.

**Comment by geerlingguy** [comment]
See: https://github.com/ansible/ansible-modules-core/issues/2921

What version of Ansible are you running?

**Comment by Rade333** [comment]
Ah, I had just a bit too old version of Ansible. Upgraded to 2.0.2.0 and now the task was successful.

Thanks!

**Comment by geerlingguy** [comment]
Great!
