### ISSUE TITLE
Feature Request: support master-slave configuration

### ISSUE THREAD

**Issue by mrPsycho** [geerlingguy/ansible-role-solr#32]
Hello!

Thank for this role, it is very useful!

and - will you add support of clusters?

**Comment by itxx00** [comment]
+1

**Comment by geerlingguy** [comment]
Possibly... It's not that difficult to set the configuration for Solr Cloud / clustering, it just takes some time to test, and I might not be able to get easy testing inside Travis with multiple Docker containers... but we'll see!

**Comment by denics** [comment]
Hi all, just reopening this :)
