### ISSUE TITLE
Release 3.2.3 requires Ansible 2.2 and this has not been specified in the release notes

### ISSUE THREAD

**Issue by anavarre** [geerlingguy/ansible-role-solr#49]
https://docs.ansible.com/ansible/systemd_module.html reports that `systemd` module is available as of Ansible 2.2

This should be mentioned somewhere in the release notes at https://github.com/geerlingguy/ansible-role-solr/releases/tag/3.2.3 to prevent people from hitting a wall when running the `install.yml` playbook.

**Comment by geerlingguy** [comment]
Sorry about that! I think the best option is to pull that tag and bump it to 3.3.0, in order to not break people's playbooks when they're on older Ansible versions. Good catch!

**Comment by geerlingguy** [comment]
Fixed via 3.2.4 and 3.3.0/1 releases.
