### ISSUE TITLE
Solr 5.3.1, solr.in.sh doesn't exist (centos7)

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/ansible-role-solr#50]
See geerlingguy/drupal-vm#1028

```
TASK [geerlingguy.solr : Apply Solr memory configuration changes.] *************
failed: [drupalvm] (item={u'regexp': u'^.?SOLR_JAVA_MEM=', u'line': u'SOLR_JAVA_MEM="-Xms64M -Xmx128M"'}) => {"failed": true, "item": {"line": "SOLR_JAVA_MEM=\"-Xms64M -Xmx128M\"", "regexp": "^.?SOLR_JAVA_MEM="}, "msg": "Destination /etc/default/solr.in.sh does not exist !", "rc": 257}
failed: [drupalvm] (item={u'regexp': u'^SOLR_PORT=', u'line': u'SOLR_PORT="8983"'}) => {"failed": true, "item": {"line": "SOLR_PORT=\"8983\"", "regexp": "^SOLR_PORT="}, "msg": "Destination /etc/default/solr.in.sh does not exist !", "rc": 257}
```

**Comment by geerlingguy** [comment]
To add a little background from that linked issue:

```
[vagrant@staff drupalroot]$ sudo find / -name solr.in.sh -type f
/etc/default/solr.in.sh
/root/solr-5.3.1/bin/solr.in.sh
/var/solr/solr.in.sh
/opt/solr-5.3.1/bin/solr.in.sh
```

We only point to `/etc/solr.in.sh`, but for RedHat it looks like the file is installed inside `/etc/default/solr.in.sh` instead.

**Comment by cdmo** [comment]
Thanks again @geerlingguy. Let me know if I can help any more with this!

**Comment by geerlingguy** [comment]
@cdmo - Hmm... For Solr 6.x, I see that the file is always created at `/etc/default/solr.in.sh`

I wonder if the 5.x installation is different for RHEL (or even for Ubuntu)... I'll have to retest the role locally a few different ways.

I can't get the error to reproduce when testing locally with 6.3.0.

**Comment by geerlingguy** [comment]
Also, the installer at 5.5.x installs the file directly to /etc/default (the path we have set up in the role): https://github.com/apache/lucene-solr/blob/branch_5_5/solr/bin/install_solr_service.sh#L283

@cdmo - Are you running the latest version of Drupal VM?

**Comment by geerlingguy** [comment]
I also can't get this to reproduce on an Ubuntu box. Downgrading to Vagrant 1.8.6 to try again on a CentOS box...

**Comment by geerlingguy** [comment]
Aha! I just realized that 5.3.1 installs that file inside of the `$SOLR_VAR_DIR`, instead of the default `/etc/default` directory.

Is it possible for you to use Solr 5.5.3 (or another 5.5.x version) instead?

**Comment by geerlingguy** [comment]
Since I can confirm this is working correctly with the defaults starting in 5.5.x (and possibly 5.4.x, haven't verified when), and it works the same in 6.x, I'm going to leave as-is and recommend upgrading Solr if using 5.3.x or earlier.

**Comment by cdmo** [comment]
Okie doke, no problem. I'll use 5.5.3. I was using 5.3.1 just to mirror what we have in our production environment. For dev purposes this is okay I think. Maybe I'll chat with our systems administrator about why we're using the version we're using. Thanks for taking a look.
