### ISSUE TITLE
Pre5 solr on Centos7 restart problem

### ISSUE THREAD

**Issue by bibliotechy** [geerlingguy/ansible-role-solr#51]
I'm having an issue with restarting solr 4.10 on Centos 7. Calling restart via the handler causes solr to stop, but it does not restart.

I've already hit an issue with solr not starting due to the daemon needing to be reloaded, so I've copied the 5+ logic into the `pre5-install.yml` [tasks](https://github.com/bibliotechy/ansible-role-solr/blob/pre5-rhel7-workaround/tasks/install-pre5.yml#L68-L74) but I'm really having trouble sussing out why the restart command is not working.

If I run the commands at the command line, I see a similar issue. If I have a running solr and issue `systemctl restart solr`, the solr process stops (the log ends with `org.eclipse.jetty.util.thread.ShutdownThread  – shutdown already commenced` , but is not restarted.

If I then issue a `systemctl status solr` it outputs:
```
● solr.service - SYSV: Controls an Apache Solr process.
   Loaded: loaded (/etc/rc.d/init.d/solr)
   Active: active (exited) since Thu 2016-12-15 19:48:37 UTC; 2min 35s ago
     Docs: man:systemd-sysv-generator(8)

Dec 15 19:48:37 dangerzone.mydomain systemd[1]: Starting SYSV: Controls an Apache Solr process....
Dec 15 19:48:37 dangerzone.mydomain solr[12063]: Starting solr... already started... done.
Dec 15 19:48:37 dangerzone.mydomain systemd[1]: Started SYSV: Controls an Apache Solr process..
```
Any thoughts? Happy to test things and submit a PR if you can point me in the right direction.

**Comment by geerlingguy** [comment]
@bibliotechy - Sorry about the delay in responding—yes, this was a bug, and it looks like it may be fixed in the next role version, via https://github.com/geerlingguy/ansible-role-solr/issues/53 and #55
