### ISSUE TITLE
Using the new solr.xml format

### ISSUE THREAD

**Issue by rajasaur** [geerlingguy/ansible-role-solr#7]
The new solr.xml format (https://cwiki.apache.org/confluence/display/solr/Format+of+solr.xml) makes it a lot easier to auto-discover cores and removes the need for hardcoding the 2 cords that are currently mentioned in this role. We will still need a default core, but the configuration is much simplified as per the above example. 

I was able to modify your role using the above to get this to work, the only quirk being that solrconfig.xml has relative paths to some of the jars in the "contrib" and "dist" folder which I had to fix manually (but can be done through the role itself).  This wasnt a problem in the way the role is currently available but inside example/multicore/core0/conf/solrconfig.xml is this statement
````
<!--
 This is a stripped down config file used for a simple example...
 It is *not* a good example to work from.
-->
```

Instead using the example/solr/collection1/conf/solrconfig.xml has a more complete configuration file, but has the reference issue that I mentioned above.

I can provide a PR if thats okay with you, quite new to ansible roles, so might need some work before I send it out to you.

**Comment by geerlingguy** [comment]
This has been handily resolved due to my laziness—with Solr 5.x/6.x, the install is managed by Solr itself, and you can create cores via `bin/solr create -c [core-name-here]` — see #25 for more info.
