### ISSUE TITLE
Ansible Container warning

### ISSUE THREAD

**Issue by longwave** [geerlingguy/ansible-role-solr#78]
I am getting a new warning when using this role in a build:
```
- downloading role 'solr', owned by geerlingguy
[WARNING]: geerlingguy.solr is a Container Enabled role and should only be installed using Ansible Container
```
Though looking at https://github.com/geerlingguy/solr-container it seems this role is meant to work both with Ansible Container and standalone, and this can be ignored, is that right? Is there a way to suppress this warning?

**Comment by geerlingguy** [comment]
Whaaa? Yikes, I thought if you added the container compatibility layer, then that would be a nice added bonus to some roles, not something that scares non-container-using people with a big warning.

Opened upstream issue here: https://github.com/ansible/ansible/issues/27537

**Comment by geerlingguy** [comment]
To be clear: This role works perfectly fine whether being used with ansible-container or not. The only place _I'm_ currently using it with ansible-container is for: https://github.com/geerlingguy/solr-container

Everywhere else, I'm using it without ansible-container.

**Comment by geerlingguy** [comment]
@longwave - Thanks again for reporting! This has been fixed in `devel` upstream: https://github.com/ansible/ansible/pull/27578
