### ISSUE TITLE
Install issue on CentOS 6

### ISSUE THREAD

**Issue by longwave** [geerlingguy/ansible-role-solr#79]
On a pre-Solr 5 install on CentOS 6 I am getting an error, because systemd is not installed:

```
TASK [geerlingguy.solr : Copy solr systemd unit file into place (for systemd systems).] ***
fatal: [127.0.0.1]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/systemd/system does not exist"}
```

I don't immediately see why this is happening because the `when` clause should be skipping this step:
```
$ ansible -ilocalhost, all --connection local -m setup -a 'filter=ansible_distribution*'
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "CentOS", 
        "ansible_distribution_major_version": "6", 
        "ansible_distribution_release": "Final", 
        "ansible_distribution_version": "6.9"
    }, 
    "changed": false
}
```

Would it be simpler to check for the existence of the directory and put the unit file into place only if it exists?

**Comment by geerlingguy** [comment]
@longwave - Strange, I have this working on a few CentOS 6 servers, so I wonder if maybe in the playbook you're using, you might have `gather_facts: no`? Or maybe for some other reason the `ansible_distribution` and `ansible_distribution_major_version` vars aren't getting set?

**Comment by longwave** [comment]
I have `gather_facts: yes` set, and even if the vars weren't set somehow I would still expect it to be skipped as the `when` clause should equate to false, so I also find this a bit strange. For now I have worked around it by making the directory in `pre_tasks` so the role can place the unit file even if it isn't used; I will try to debug properly if I get time to do so.

**Comment by longwave** [comment]
The debug output above gave me a clue: the quotes around `ansible_distribution_major_version` mean it is treated as a string and not an integer. This is an upstream issue: https://github.com/ansible/ansible/issues/15817 - but it looks like it can be worked around by casting the variable to int before using it.

**Comment by geerlingguy** [comment]
Ah, that makes sense.
