### ISSUE TITLE
ansible-role-solr/tasks/cores.yml cannot be run with --check

### ISSUE THREAD

**Issue by cherouvim** [geerlingguy/ansible-role-solr#84]
In `--check` mode the task `Check current list of Solr cores.` is skipped thus `solr_cores_current` is never populated. This means that the subsequent `Ensure Solr conf directories exist.` fails with:

    FAILED! => {"failed": true, "msg": "The conditional check 'item not in solr_cores_current.content' failed. The error was: error while evaluating conditional (item not in solr_cores_current.content): Unable to look up a name or access an attribute in template string ({% if item not in solr_cores_current.content %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable

**Comment by cherouvim** [comment]
One, maybe crude, way to solve this is to add `ignore_errors: yes` on tasks which depend on the `solr_cores_current.content` variable.

**Comment by geerlingguy** [comment]
Merged the PR, thanks!
