### ISSUE TITLE
"Create configured cores" task fails when solr is running on an alternate port 

### ISSUE THREAD

**Issue by dale-c-anderson** [geerlingguy/ansible-role-solr#98]
I was playing around with setting up multiple solr versions side by side. I have solr 5 already installed in the default location, running on the default port. 

I ran in to this trying to add solr 6 beside it: 
```json
{"changed": true, "cmd": "/opt/solr6/bin/solr create -c collection1", "delta": "0:00:01.263591", "end": "2018-06-08 21:50:14.956845", "failed": true, "item": "collection1", "msg": "non-zero return code", "rc": 1, "start": "2018-06-08 21:50:13.693254", "stderr": "\nERROR: \nCore 'collection1' already exists!\nChecked core existence using Core API command:\nhttp://localhost:8983/solr/admin/cores?action=STATUS&core=collection1", "stderr_lines": ["", "ERROR: ", "Core 'collection1' already exists!", "Checked core existence using Core API command:", "http://localhost:8983/solr/admin/cores?action=STATUS&core=collection1"], "stdout": "", "stdout_lines": []}
```

It looks like `bin/solr` assumes solr is running on port 8983 unless the alternate port is specified as a command line option. 

It was easy to fix manually, I just needed to add `-p <port>` to the `bin/solr create` command. 

I'll create a PR to fix the ansible task.

**Comment by geerlingguy** [comment]
Eek, good catch!
